name: airflow-dockerised

services:
  airflow_postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
    restart: always

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow_init
    env_file:
      - ../airflow/.env
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    entrypoint: >
      /bin/bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Vipul --lastname Parasar --role Admin --email vipul.parasar.global@gmail.com || true
      "
    depends_on:
      airflow_postgres:
        condition: service_healthy
    restart: on-failure

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    env_file:
      - ../airflow/.env
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      airflow_postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_webserver
    env_file:
      - ../airflow/.env
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow_postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always

volumes:
  postgres-db-volume: