name: airflow-dockerised

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - kafka-net

  airflow-init:
    image: apache/airflow:2.7.3
    container_name: airflow-init
    env_file:
      - ../airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --firstname Vipul \
          --lastname Parasar \
          --role Admin \
          --email vipul.parasar.global@gmail.com \
          --password admin123 || true
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    networks:
      - kafka-net
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow_webserver
    depends_on:
      - postgres
    env_file:
      - ../airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - kafka-net

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow_scheduler
    depends_on:
      - postgres
    env_file:
      - ../airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - kafka-net

volumes:
  postgres-db-volume:

networks:
  kafka-net:
    external: true